version: "3.9"

services:
  backend:
    image: m2c_v2-backend:latest
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      PORT: "9000"
      JAVA_TOOL_OPTIONS: "-Djava.net.preferIPv4Stack=true"
    restart: unless-stopped

  yjs:
    image: m2c_v2-yjs:latest
    ports:
      - "1234:1234"
    env_file:
      - .env
    environment:
      PORT: "1234"
    restart: unless-stopped

  peer:
    image: m2c_v2-peer:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      PORT: "8080"
    restart: unless-stopped

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   environment:
  #     PORT: "3000"
  #   restart: unless-stopped
